# Usar uma imagem base com Python
FROM python:3.9-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos do projeto
COPY . /app

# Instalar as dependências
RUN pip install --no-cache-dir flask

# Expor a porta 80
EXPOSE 80

# Comando para rodar a aplicação
CMD ["python", "app.py"]

